# Generated by Django 5.2.5 on 2025-11-10 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traduccionia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traduccionia',
            name='idioma_destino',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traduccionia',
            name='idioma_origen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='traduccionia',
            name='texto_traducido',
            field=models.TextField(),
        ),
    ]
