# Generated by Django 5.2.5 on 2025-11-11 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto1', '0002_traduccionia_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traduccionia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
