# Generated by Django 5.2.5 on 2025-11-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto1', '0004_remove_usuario_tipo_usuario_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
    ]
