# Generated by Django 5.2.5 on 2025-12-04 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto1', '0006_notificacion_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='leida',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='usuario_relacionado',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.CharField(max_length=255),
        ),
    ]
