# Generated by Django 5.2.5 on 2025-11-09 23:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(blank=True, max_length=100)),
                ('log_acciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=150)),
                ('fecha_emision', models.DateField()),
                ('autor', models.CharField(blank=True, max_length=200)),
                ('formato', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('nivel_tecnologico', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('protocolo', models.CharField(blank=True, max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TraduccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('texto_traducido', models.TextField(blank=True, null=True)),
                ('idioma_origen', models.CharField(default='es', max_length=50)),
                ('idioma_destino', models.CharField(default='en', max_length=50)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('paciente', 'Paciente')], default='paciente', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DatosClinicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_original', models.CharField(max_length=200)),
                ('valor_original', models.TextField()),
                ('valor_estandarizado', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField()),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='appProyecto1.documentoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=50)),
                ('preferred_term', models.CharField(max_length=255)),
                ('synonyms', models.TextField(blank=True)),
                ('language', models.CharField(default='es', max_length=10)),
            ],
            options={
                'unique_together': {('code', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('rut', models.CharField(max_length=30, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('identificador_nacional', models.CharField(max_length=12, unique=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='appProyecto1.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('tipo_acceso', models.CharField(blank=True, max_length=100)),
                ('diagnostico_principal', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(blank=True, max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='appProyecto1.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='documentoclinico',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='appProyecto1.sistemaorigen'),
        ),
        migrations.CreateModel(
            name='FHIRObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='final', max_length=20)),
                ('categoria', models.CharField(default='translation', max_length=50)),
                ('codigo', models.CharField(default='Texto médico traducido', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto1.documentoclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_fhir', to='appProyecto1.paciente')),
                ('traduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appProyecto1.traduccionia')),
            ],
        ),
    ]
