# Generated by Django 5.2.5 on 2025-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto1', '0003_alter_traduccionia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('administrador', 'Administrador')], default='doctor', max_length=30),
        ),
    ]
